<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon />
    <StartupObject>ARCYN.UI.App</StartupObject>
    <AssemblyName>ARCYN</AssemblyName>
    <Version>1.5.1</Version>
    <RootNamespace>ARCYN.UI</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="8.0.1" />
    <PackageReference Include="System.Management" Version="9.0.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ARCYN.Core\ARCYN.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Services\ConfigService.cs" />
    <Compile Remove="Services\LogService.cs" />
    <Compile Remove="Services\ModeService.cs" />
    <Compile Remove="Services\LaunchOrchestrator.cs" />
    <Compile Remove="Services\LaunchService.cs" />
    <Compile Remove="Models\ArcynConfig.cs" />
    <Compile Remove="Models\ModeConfig.cs" />
    <Compile Remove="Models\ModeConfig.UI.cs" />
    <Compile Remove="AppState.cs" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Fonts\*" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\example.arcyn.json" Link="example.arcyn.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>



  <ItemGroup>
    <ProjectReference Include="..\\ARCYN.Platform\\ARCYN.Platform.csproj" />
  </ItemGroup>
</Project>
